-- Portal schema. ${json}/${blob} placeholders keep the script portable between PostgreSQL and H2 (mock profile).

CREATE TABLE inventory_page (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(80)  NOT NULL UNIQUE,
    name          VARCHAR(120) NOT NULL,
    description   VARCHAR(500),
    icon          VARCHAR(60),
    group_name    VARCHAR(80),
    sort_order    INT          NOT NULL DEFAULT 0,
    system_page   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE inventory_column (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id          BIGINT       NOT NULL REFERENCES inventory_page (id) ON DELETE CASCADE,
    col_key          VARCHAR(80)  NOT NULL,
    label            VARCHAR(120) NOT NULL,
    col_type         VARCHAR(30)  NOT NULL,
    required         BOOLEAN      NOT NULL DEFAULT FALSE,
    locked           BOOLEAN      NOT NULL DEFAULT FALSE,
    visible          BOOLEAN      NOT NULL DEFAULT TRUE,
    width            INT,
    sort_order       INT          NOT NULL DEFAULT 0,
    options          ${json},
    expiry_tracking  BOOLEAN      NOT NULL DEFAULT FALSE,
    description      VARCHAR(500),
    CONSTRAINT uq_inventory_column UNIQUE (page_id, col_key)
);

CREATE TABLE inventory_record (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id     BIGINT NOT NULL REFERENCES inventory_page (id) ON DELETE CASCADE,
    data        ${json} NOT NULL,
    created_by  VARCHAR(120),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by  VARCHAR(120),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_inventory_record_page ON inventory_record (page_id);

CREATE TABLE user_view_pref (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(120) NOT NULL,
    view_key    VARCHAR(200) NOT NULL,
    pref_value  ${json} NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_user_view_pref UNIQUE (username, view_key)
);

CREATE TABLE integration_setting (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key   VARCHAR(120) NOT NULL UNIQUE,
    setting_type  VARCHAR(40)  NOT NULL,
    config        ${json},
    secrets       VARCHAR(8000),
    updated_by    VARCHAR(120),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE alert (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key       VARCHAR(300) NOT NULL,
    source           VARCHAR(40)  NOT NULL,
    severity         VARCHAR(20)  NOT NULL,
    title            VARCHAR(300) NOT NULL,
    message          VARCHAR(4000),
    resource         VARCHAR(300),
    status           VARCHAR(20)  NOT NULL,
    occurrences      INT          NOT NULL DEFAULT 1,
    first_seen       TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen        TIMESTAMP WITH TIME ZONE NOT NULL,
    acknowledged_by  VARCHAR(120),
    acknowledged_at  TIMESTAMP WITH TIME ZONE,
    resolved_at      TIMESTAMP WITH TIME ZONE
);
CREATE INDEX ix_alert_status ON alert (status);
CREATE INDEX ix_alert_dedupe ON alert (dedupe_key);

CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts           TIMESTAMP WITH TIME ZONE NOT NULL,
    username     VARCHAR(120) NOT NULL,
    user_role    VARCHAR(40),
    action       VARCHAR(80)  NOT NULL,
    target_type  VARCHAR(60)  NOT NULL,
    target_id    VARCHAR(300),
    details      ${json},
    client_ip    VARCHAR(80),
    success      BOOLEAN      NOT NULL DEFAULT TRUE,
    error        VARCHAR(2000)
);
CREATE INDEX ix_audit_ts ON audit_log (ts);

CREATE TABLE connectivity_target (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(120) NOT NULL,
    test_type             VARCHAR(10)  NOT NULL,
    host                  VARCHAR(300),
    port                  INT,
    url                   VARCHAR(1000),
    http_method           VARCHAR(10),
    expected_status       INT,
    timeout_ms            INT          NOT NULL DEFAULT 5000,
    schedule_type         VARCHAR(10)  NOT NULL DEFAULT 'NONE',
    interval_seconds      INT,
    cron                  VARCHAR(120),
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    failure_threshold     INT          NOT NULL DEFAULT 3,
    consecutive_failures  INT          NOT NULL DEFAULT 0,
    last_status           VARCHAR(10),
    last_run_at           TIMESTAMP WITH TIME ZONE,
    last_latency_ms       BIGINT,
    tags                  VARCHAR(500),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE connectivity_result (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id     BIGINT REFERENCES connectivity_target (id) ON DELETE CASCADE,
    ts            TIMESTAMP WITH TIME ZONE NOT NULL,
    test_type     VARCHAR(10)   NOT NULL,
    target_desc   VARCHAR(1000) NOT NULL,
    success       BOOLEAN       NOT NULL,
    latency_ms    BIGINT,
    message       VARCHAR(2000),
    details       ${json},
    triggered_by  VARCHAR(120)
);
CREATE INDEX ix_conn_result_target_ts ON connectivity_result (target_id, ts);

CREATE TABLE kafka_health_snapshot (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id        BIGINT       NOT NULL,
    instance_name      VARCHAR(200),
    ts                 TIMESTAMP WITH TIME ZONE NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    brokers_online     INT,
    brokers_total      INT,
    topics             INT,
    under_replicated   INT,
    connectors_total   INT,
    connectors_failed  INT,
    max_lag            BIGINT,
    message            VARCHAR(2000)
);
CREATE INDEX ix_kafka_health_instance_ts ON kafka_health_snapshot (instance_id, ts);

CREATE TABLE shedlock (
    name        VARCHAR(64)  NOT NULL PRIMARY KEY,
    lock_until  TIMESTAMP    NOT NULL,
    locked_at   TIMESTAMP    NOT NULL,
    locked_by   VARCHAR(255) NOT NULL
);

-- Used by JdbcOAuth2AuthorizedClientService so GitHub user tokens survive across replicas.
CREATE TABLE oauth2_authorized_client (
    client_registration_id   VARCHAR(100)  NOT NULL,
    principal_name           VARCHAR(200)  NOT NULL,
    access_token_type        VARCHAR(100)  NOT NULL,
    access_token_value       ${blob}       NOT NULL,
    access_token_issued_at   TIMESTAMP     NOT NULL,
    access_token_expires_at  TIMESTAMP     NOT NULL,
    access_token_scopes      VARCHAR(1000) DEFAULT NULL,
    refresh_token_value      ${blob}       DEFAULT NULL,
    refresh_token_issued_at  TIMESTAMP     DEFAULT NULL,
    created_at               TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (client_registration_id, principal_name)
);
