-- Alert lifecycle: typed alerts, pending/firing/escalation/notification bookkeeping, snooze and resolution details.
ALTER TABLE alert ADD COLUMN alert_type VARCHAR(60);
ALTER TABLE alert ADD COLUMN fired_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE alert ADD COLUMN cleared_since TIMESTAMP WITH TIME ZONE;
ALTER TABLE alert ADD COLUMN last_notified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE alert ADD COLUMN next_notify_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE alert ADD COLUMN notification_count INT DEFAULT 0 NOT NULL;
ALTER TABLE alert ADD COLUMN escalation_level INT DEFAULT 0 NOT NULL;
ALTER TABLE alert ADD COLUMN snoozed_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE alert ADD COLUMN snoozed_by VARCHAR(120);
ALTER TABLE alert ADD COLUMN reopen_count INT DEFAULT 0 NOT NULL;
ALTER TABLE alert ADD COLUMN resolved_by VARCHAR(120);
ALTER TABLE alert ADD COLUMN resolved_reason VARCHAR(300);
CREATE INDEX ix_alert_type ON alert (alert_type);

-- One row per alert type; missing rows fall back to the built-in defaults of AlertType.
CREATE TABLE alert_rule (
    alert_type             VARCHAR(60)  NOT NULL PRIMARY KEY,
    enabled                BOOLEAN      NOT NULL DEFAULT TRUE,
    severity               VARCHAR(20)  NOT NULL,
    min_occurrences        INT          NOT NULL DEFAULT 1,
    pending_seconds        INT          NOT NULL DEFAULT 0,
    repeat_minutes         INT          NOT NULL DEFAULT 60,
    backoff_multiplier     DOUBLE PRECISION NOT NULL DEFAULT 2,
    max_repeat_minutes     INT          NOT NULL DEFAULT 720,
    max_notifications      INT          NOT NULL DEFAULT 0,
    notify_on_resolve      BOOLEAN      NOT NULL DEFAULT TRUE,
    resolve_grace_seconds  INT          NOT NULL DEFAULT 0,
    stale_minutes          INT          NOT NULL DEFAULT 0,
    reopen_window_minutes  INT          NOT NULL DEFAULT 30,
    email_enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    email_recipients       VARCHAR(2000),
    teams_enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    escalation             ${json},
    params                 ${json},
    muted_until            TIMESTAMP WITH TIME ZONE,
    mute_reason            VARCHAR(300),
    updated_by             VARCHAR(120),
    updated_at             TIMESTAMP WITH TIME ZONE
);

CREATE TABLE alert_event (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id   BIGINT       NOT NULL REFERENCES alert (id) ON DELETE CASCADE,
    ts         TIMESTAMP WITH TIME ZONE NOT NULL,
    kind       VARCHAR(40)  NOT NULL,
    channel    VARCHAR(20),
    success    BOOLEAN,
    message    VARCHAR(2000),
    actor      VARCHAR(120)
);
CREATE INDEX ix_alert_event_alert ON alert_event (alert_id, ts);

-- Slack-style webhook setting is replaced by EMAIL and TEAMS channels.
DELETE FROM integration_setting WHERE setting_type = 'NOTIFICATIONS';
